In [129]:
import pandas as pd
import numpy as np

In [130]:
S1=pd.Series()
S1

Series([], dtype: float64)

In [131]:
S2=pd.Series([1,3,5,7,9], \
    index=['a','b','c','d','e'])
S2
S2.values
S2.index
S2['f']=11
S2

a     1
b     3
c     5
d     7
e     9
f    11
dtype: int64

In [132]:
pd.Series({'a': 1,'b': 3,'c': 5,'d': 7})

S3=pd.Series([1, 3, -5, 7])
S3

0    1
1    3
2   -5
3    7
dtype: int64

In [133]:
np.random.seed(54321)
pd.Series(np.random.randn(5))

0    0.223979
1    0.744591
2   -0.334269
3    1.389172
4   -2.296095
dtype: float64

In [134]:
pd.Series(np.arange(2, 6))

S4=pd.Series([0,np.NaN,2,4,6,8,\
              True, 10, 12])
S4.head()
S4.head(3)
S4.tail()
S4.tail(6)
S4.take([2,4,0])

2    2
4    6
0    0
dtype: object

In [135]:
S5= pd.Series([1,3,5,7,9],\
     index=['a','b','c','d','e'])
S5[2],S5['d']

S5[[1,3,4]]
S5[['b','e','d']]
S5[0:4]
S5['a':'d']

a    1
b    3
c    5
d    7
dtype: int64

In [136]:
from datetime import datetime
import pandas as pd

In [137]:
date = datetime(2016,1,1)
date = pd.Timestamp(date)
date
type(date)
ts=pd.Series(1,index=[date])
ts
ts.index
ts.index[0]

Timestamp('2016-01-01 00:00:00')

In [138]:
dates = ['2016-01-01','2016-01-02','2016-01-03']
ts=pd.Series([1,2,3],index=pd.to_datetime(dates))
ts 
ts.index 
ts.index[0] 

Timestamp('2016-01-01 00:00:00')

In [139]:
dates = [datetime(2016,1,1),datetime(2016,1,2),datetime(2016,1,3)]
ts=pd.Series([1,2,3],index=dates)
ts.index[0] 
ts['20160101']
ts['2016-01-01']
ts['01/01/2016']

1

In [140]:
ts
ts['2016']
ts['2016-01':'2016-02']
ts.truncate(after='2016-01-02') 
ts.shift(1) #正数为滞后
ts.shift(-1) #负数为超前

price=pd.Series([20.34,20.56,21.01,20.65,21.34],\
                index=pd.to_datetime(['2016-01-01','2016-01-02',\
                '2016-01-03','2016-01-04','2016-01-05']))
(price-price.shift(1))/price.shift(1) 

2016-01-01         NaN
2016-01-02    0.010816
2016-01-03    0.021887
2016-01-04   -0.017135
2016-01-05    0.033414
dtype: float64

In [141]:
ts.index.freq is None 
rts=ts.resample('M',how='first') #'M'指的是每月最后一天
rts 
rts=ts.resample('MS',how='first') #'MS'指的是每月的第一天
rts 

E:\Data_analysis_plan\python_36_install\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: how in .resample() is deprecated
the new syntax is .resample(...).first()
  
E:\Data_analysis_plan\python_36_install\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: how in .resample() is deprecated
the new syntax is .resample(...).first()
  after removing the cwd from sys.path.


2016-01-01    1
Freq: MS, dtype: int64

In [142]:
import pandas as pd
import numpy as np

In [143]:
dates = ['2016-01-01','2016-01-02','2016-01-03',
         '2016-01-04','2016-01-05','2016-01-06']
dates=pd.to_datetime(dates)
dates

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06'],
              dtype='datetime64[ns]', freq=None)

# 由于随机的关系，接下来跑出的结果会和书上内容不同

In [144]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
df

A         B         C         D
2016-01-01  1.141205  0.055448 -0.082760 -0.651688
2016-01-02 -0.016022 -0.574465  0.048143  0.499497
2016-01-03  0.155397  0.762543  0.560489  0.332483
2016-01-04 -0.545423  0.592000 -0.565781 -0.120315
2016-01-05  0.429711 -0.553929  0.305712  0.219993
2016-01-06  0.992988  0.720928  0.338761 -0.482821

In [145]:
df.head(3)
df.tail(4)
df.columns
df.index
df.values
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.359643  0.167087  0.100760 -0.033808
std    0.635430  0.620336  0.397675  0.463437
min   -0.545423 -0.574465 -0.565781 -0.651688
25%    0.026833 -0.401585 -0.050034 -0.392195
50%    0.292554  0.323724  0.176927  0.049839
75%    0.852169  0.688696  0.330498  0.304361
max    1.141205  0.762543  0.560489  0.499497

In [146]:
df[1:3]
df['A']
df[['A','C']]
df[df['A']>0]
df.loc[:,'A']
df.loc[:,'A':'C']
df.loc[dates[0:2],'A':'C']
df.loc[dates[0],'A']
df.at[dates[0],'A']
df.loc[df.loc[:,'A']>0]

A         B         C         D
2016-01-01  1.141205  0.055448 -0.082760 -0.651688
2016-01-03  0.155397  0.762543  0.560489  0.332483
2016-01-05  0.429711 -0.553929  0.305712  0.219993
2016-01-06  0.992988  0.720928  0.338761 -0.482821

In [147]:
df.iloc[2]
df.iloc[:,2]
df.iloc[[1,4],[2,3]]
df.iloc[1:4,2:4]
df.iloc[3,3]
df.iat[3,3]
df.loc[:,df.iloc[3]>0]

B
2016-01-01  0.055448
2016-01-02 -0.574465
2016-01-03  0.762543
2016-01-04  0.592000
2016-01-05 -0.553929
2016-01-06  0.720928

In [148]:
df.ix[2:5]
df.ix[[1,3],2]
df.ix[[1,3],'C']
df.ix[1:3,'A':'C']
df.ix[1:3,df.iloc[3]>0]

E:\Data_analysis_plan\python_36_install\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


B
2016-01-02 -0.574465
2016-01-03  0.762543

# python的sort()函数详解 http://blog.csdn.net/robinson_/article/details/51484147

In [149]:
df.T
df.sort_index(axis=0, ascending=False)
df.sort_index(axis=1, ascending=False)
df.sort_index(by='C')
df
df.rank(axis=0)
df.rank(axis=1,ascending=False)

E:\Data_analysis_plan\python_36_install\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  after removing the cwd from sys.path.


A    B    C    D
2016-01-01  1.0  2.0  3.0  4.0
2016-01-02  3.0  4.0  2.0  1.0
2016-01-03  4.0  1.0  2.0  3.0
2016-01-04  3.0  1.0  4.0  2.0
2016-01-05  1.0  4.0  2.0  3.0
2016-01-06  1.0  2.0  3.0  4.0

In [150]:
s1=pd.Series([1,2,3,4,5,6],index=pd.date_range('20160102',periods=6))
s1
df['E'] = s1
df
df=df[list('ABCD')]
pd.concat([df, s1], axis=1)

A         B         C         D    0
2016-01-01  1.141205  0.055448 -0.082760 -0.651688  NaN
2016-01-02 -0.016022 -0.574465  0.048143  0.499497  1.0
2016-01-03  0.155397  0.762543  0.560489  0.332483  2.0
2016-01-04 -0.545423  0.592000 -0.565781 -0.120315  3.0
2016-01-05  0.429711 -0.553929  0.305712  0.219993  4.0
2016-01-06  0.992988  0.720928  0.338761 -0.482821  5.0
2016-01-07       NaN       NaN       NaN       NaN  6.0

In [151]:
df1=pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]},\
                index=pd.date_range('20160110',periods=3))
df1 
df.append(df1)
pd.concat([df,df1],join='inner')
df.drop(dates[1:3]) 
df.drop('A',axis=1) 
del df['A']
df

B         C         D
2016-01-01  0.055448 -0.082760 -0.651688
2016-01-02 -0.574465  0.048143  0.499497
2016-01-03  0.762543  0.560489  0.332483
2016-01-04  0.592000 -0.565781 -0.120315
2016-01-05 -0.553929  0.305712  0.219993
2016-01-06  0.720928  0.338761 -0.482821

In [152]:
df.loc[dates[2],'C'] = 0
df.iloc[0,2] = 0
df.loc[:,'B'] = np.arange(0,len(df))
df

E:\Data_analysis_plan\python_36_install\lib\site-packages\pandas\core\indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
E:\Data_analysis_plan\python_36_install\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
E:\Data_analysis_plan\python_36_install\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
E:\Data

B         C         D
2016-01-01  0 -0.082760  0.000000
2016-01-02  1  0.048143  0.499497
2016-01-03  2  0.000000  0.332483
2016-01-04  3 -0.565781 -0.120315
2016-01-05  4  0.305712  0.219993
2016-01-06  5  0.338761 -0.482821

In [153]:
new_index=pd.date_range('20160102',periods=7)
df.reindex(new_index,columns=list('ABCD'))

A    B         C         D
2016-01-02 NaN  1.0  0.048143  0.499497
2016-01-03 NaN  2.0  0.000000  0.332483
2016-01-04 NaN  3.0 -0.565781 -0.120315
2016-01-05 NaN  4.0  0.305712  0.219993
2016-01-06 NaN  5.0  0.338761 -0.482821
2016-01-07 NaN  NaN       NaN       NaN
2016-01-08 NaN  NaN       NaN       NaN

In [154]:
import pandas as pd 
import numpy as np

In [155]:
s1=pd.Series([1,2,3],index=list('ABC'))
s1
s2=pd.Series([4,5,6],index=list('BCD'))
s2
s1+s2

A    NaN
B    6.0
C    8.0
D    NaN
dtype: float64

In [156]:
df1=pd.DataFrame(np.arange(1,13).reshape(3,4),
                 index=list('abc'),columns=list('ABCD'))
df1 

A   B   C   D
a  1   2   3   4
b  5   6   7   8
c  9  10  11  12

In [157]:
df1-s1

A    B    C   D
a  0.0  0.0  0.0 NaN
b  4.0  4.0  4.0 NaN
c  8.0  8.0  8.0 NaN

In [158]:
df2=pd.DataFrame(np.arange(1,13).reshape(4,3),
                 index=list('bcde'),columns=list('CDE'))
df2 

C   D   E
b   1   2   3
c   4   5   6
d   7   8   9
e  10  11  12

In [159]:
df1*df2

A   B     C     D   E
a NaN NaN   NaN   NaN NaN
b NaN NaN   7.0  16.0 NaN
c NaN NaN  44.0  60.0 NaN
d NaN NaN   NaN   NaN NaN
e NaN NaN   NaN   NaN NaN

In [160]:
df1

A   B   C   D
a  1   2   3   4
b  5   6   7   8
c  9  10  11  12

In [161]:
df2

C   D   E
b   1   2   3
c   4   5   6
d   7   8   9
e  10  11  12

In [162]:
df1.div(df2,fill_value=0)

A    B         C         D    E
a  inf  inf       inf       inf  NaN
b  inf  inf  7.000000  4.000000  0.0
c  inf  inf  2.750000  2.400000  0.0
d  NaN  NaN  0.000000  0.000000  0.0
e  NaN  NaN  0.000000  0.000000  0.0

In [163]:
df0 = pd.DataFrame(np.random.rand(6,4),
                   index=pd.date_range('20160101',periods=6),
                    columns=list('ABCD'))
df0

A         B         C         D
2016-01-01  0.460703  0.816532  0.632180  0.645103
2016-01-02  0.455040  0.562814  0.670125  0.645266
2016-01-03  0.046710  0.261600  0.008384  0.857218
2016-01-04  0.030585  0.843959  0.491000  0.808222
2016-01-05  0.102852  0.874662  0.424479  0.800346
2016-01-06  0.233507  0.413949  0.062330  0.927309

In [164]:
df0.apply(max,axis=0)
f=lambda x: x.max()-x.min()
df0.apply(f,axis=1)

2016-01-01    0.355829
2016-01-02    0.215085
2016-01-03    0.848834
2016-01-04    0.813374
2016-01-05    0.771810
2016-01-06    0.864979
Freq: D, dtype: float64

In [165]:
df1

A   B   C   D
a  1   2   3   4
b  5   6   7   8
c  9  10  11  12

In [166]:
df2

C   D   E
b   1   2   3
c   4   5   6
d   7   8   9
e  10  11  12

In [167]:
df3=df1.mul(df2,fill_value=0)
df3

A    B     C     D    E
a  0.0  0.0   0.0   0.0  NaN
b  0.0  0.0   7.0  16.0  0.0
c  0.0  0.0  44.0  60.0  0.0
d  NaN  NaN   0.0   0.0  0.0
e  NaN  NaN   0.0   0.0  0.0

In [168]:
df3.isnull()
df3.notnull()
df3.B[df3.B.notnull()]

a    0.0
b    0.0
c    0.0
Name: B, dtype: float64

In [169]:
df4=pd.DataFrame(np.random.rand(5,4),
                 index=list('abcde'),
                columns=list('ABCD'))
df4.ix['c','A']=np.nan   
df4.ix['b':'d','C']=np.nan         
df4

E:\Data_analysis_plan\python_36_install\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.


A         B         C         D
a  0.693016  0.810947  0.485409  0.034001
b  0.104252  0.130955       NaN  0.593396
c       NaN  0.372679       NaN  0.227003
d  0.512566  0.665065       NaN  0.497945
e  0.325236  0.701885  0.848194  0.543231

In [170]:
df4.fillna(0)

A         B         C         D
a  0.693016  0.810947  0.485409  0.034001
b  0.104252  0.130955  0.000000  0.593396
c  0.000000  0.372679  0.000000  0.227003
d  0.512566  0.665065  0.000000  0.497945
e  0.325236  0.701885  0.848194  0.543231

In [171]:
df4.fillna(method='ffill')

A         B         C         D
a  0.693016  0.810947  0.485409  0.034001
b  0.104252  0.130955  0.485409  0.593396
c  0.104252  0.372679  0.485409  0.227003
d  0.512566  0.665065  0.485409  0.497945
e  0.325236  0.701885  0.848194  0.543231

In [172]:
df4.fillna(method='bfill')

A         B         C         D
a  0.693016  0.810947  0.485409  0.034001
b  0.104252  0.130955  0.848194  0.593396
c  0.512566  0.372679  0.848194  0.227003
d  0.512566  0.665065  0.848194  0.497945
e  0.325236  0.701885  0.848194  0.543231

In [173]:
df4.fillna(method='backfill',axis=1) 

A         B         C         D
a  0.693016  0.810947  0.485409  0.034001
b  0.104252  0.130955  0.593396  0.593396
c  0.372679  0.372679  0.227003  0.227003
d  0.512566  0.665065  0.497945  0.497945
e  0.325236  0.701885  0.848194  0.543231

In [174]:
df4.fillna(method='pad',limit=2)

A         B         C         D
a  0.693016  0.810947  0.485409  0.034001
b  0.104252  0.130955  0.485409  0.593396
c  0.104252  0.372679  0.485409  0.227003
d  0.512566  0.665065       NaN  0.497945
e  0.325236  0.701885  0.848194  0.543231

In [175]:
df4.fillna('missing', inplace=True)
df4

A         B         C         D
a  0.693016  0.810947  0.485409  0.034001
b  0.104252  0.130955   missing  0.593396
c   missing  0.372679   missing  0.227003
d  0.512566  0.665065   missing  0.497945
e  0.325236  0.701885  0.848194  0.543231

In [176]:
df4.ix['c','A']=np.nan                 
df4.ix['b':'d','C']=np.nan  
df4 

A         B         C         D
a  0.693016  0.810947  0.485409  0.034001
b  0.104252  0.130955       NaN  0.593396
c       NaN  0.372679       NaN  0.227003
d  0.512566  0.665065       NaN  0.497945
e  0.325236  0.701885  0.848194  0.543231

In [177]:
df4.dropna(axis=0)

A         B         C         D
a  0.693016  0.810947  0.485409  0.034001
e  0.325236  0.701885  0.848194  0.543231

In [178]:
df4.dropna(axis=1,thresh=3)
df4.dropna(axis=1,how='all')

A         B         C         D
a  0.693016  0.810947  0.485409  0.034001
b  0.104252  0.130955       NaN  0.593396
c       NaN  0.372679       NaN  0.227003
d  0.512566  0.665065       NaN  0.497945
e  0.325236  0.701885  0.848194  0.543231

In [179]:
df5=pd.DataFrame({'c1':['apple'] *3 + ['banana']*3+['apple'], 
                  'c2':['a', 'a', 3, 3, 'b', 'b','a']})
df5

c1 c2
0   apple  a
1   apple  a
2   apple  3
3  banana  3
4  banana  b
5  banana  b
6   apple  a

In [180]:
df5.duplicated()

0    False
1     True
2    False
3    False
4    False
5     True
6     True
dtype: bool

In [181]:
df5.drop_duplicates()

c1 c2
0   apple  a
2   apple  3
3  banana  3
4  banana  b

In [182]:
df5.duplicated(['c2'])

0    False
1     True
2    False
3     True
4    False
5     True
6     True
dtype: bool

In [183]:
df5.drop_duplicates(['c2'])

c1 c2
0   apple  a
2   apple  3
4  banana  b

In [184]:
import numpy as np

# 1.生成一个list，包含20以内的奇数，然后生成numpy.ndarray

In [185]:
odds = [i+1 for i in range(20) if (i+1)%2==1]
odds = np.array(odds)
odds

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# 2.生成一个tuple,包含40以内3的倍数，然后生成numpy.ndarray

In [186]:
three = tuple([i+1 for i in range(40) if (i+1)%3==0])
three = np.array(three)
three

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

# 3.找到之前生成的两个numpy.ndarray相同的数并用两种以上的方法输出新生成的numpy.ndarray前一半数据

In [187]:
same_number = odds[np.in1d(odds,three)]
#method1
print(same_number[:round(len(same_number/2))])
#method2
for i in range(round(len(same_number/2))):
    print(same_number[i])

[ 3  9 15]
3
9
15


# 4. 利用随机数生成10以内的10个浮点数创建序列

In [188]:
np.random.uniform(0,10,10)

array([ 8.9354834 ,  5.1109616 ,  8.82022337,  1.42750338,  5.43585088,
        5.04373138,  7.43985813,  8.3150884 ,  0.87958571,  9.50859358])

# 5.利用np.arange()生成一个包含20以内所有偶数的序列

In [189]:
even = np.arange(2,22,2)
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# 6.利用两种以上的方法访问上题中生成序列的最后5个数据

In [190]:
print(even[-5:])
print(even[len(even)-5:])

[12 14 16 18 20]
[12 14 16 18 20]


In [191]:
# 7.生成给定数据的DataFrame，输出转置后的第三行数据

In [192]:
import pandas as pd
data = pd.DataFrame({'id':['a','b','c','d','e','f'],'name':
    ['Alice','Bob','Charlie','David','Esther','Fanny'],'age':
        [34,36,30,29,32,36]})
       
data

age id     name
0   34  a    Alice
1   36  b      Bob
2   30  c  Charlie
3   29  d    David
4   32  e   Esther
5   36  f    Fanny

In [193]:
data.T

0    1        2      3       4      5
age      34   36       30     29      32     36
id        a    b        c      d       e      f
name  Alice  Bob  Charlie  David  Esther  Fanny

In [194]:
data.T.ix[2]

E:\Data_analysis_plan\python_36_install\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


0      Alice
1        Bob
2    Charlie
3      David
4     Esther
5      Fanny
Name: name, dtype: object

# 8、在上题的基础上加上“g,John,19”一行，将年龄设置为索引，删除第3行后输出结果

In [195]:
new = pd.DataFrame({'id':['g'],'name':['John'],'age':[19]})
data = data.append(new)
data.index = data.age

In [196]:
data

age id     name
age                 
34    34  a    Alice
36    36  b      Bob
30    30  c  Charlie
29    29  d    David
32    32  e   Esther
36    36  f    Fanny
19    19  g     John

In [197]:
data = data.drop(30)
data

age id    name
age                
34    34  a   Alice
36    36  b     Bob
29    29  d   David
32    32  e  Esther
36    36  f   Fanny
19    19  g    John