# Section 10.1.1

In [1]:
import numpy as np
array1=np.array(range(6))
print(array1)

[0 1 2 3 4 5]


In [2]:
array1.shape
array1.shape=2,3
print(array1)

[[0 1 2]
 [3 4 5]]


In [3]:
array2=array1.reshape(3,2)
print(array2)
array2.shape

[[0 1]
 [2 3]
 [4 5]]


(3, 2)

In [5]:
array1.shape
array1[1,2]=88

In [6]:
print(array1)

[[ 0  1  2]
 [ 3  4 88]]


In [7]:
print(array2)

[[ 0  1]
 [ 2  3]
 [ 4 88]]


In [8]:
array3=np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
array3.shape

(3, 3)

In [10]:
array4=np.arange(13,1,-1)
print(array4)

[13 12 11 10  9  8  7  6  5  4  3  2]


In [11]:
array4.shape=2,2,3
print(array4)

[[[13 12 11]
  [10  9  8]]

 [[ 7  6  5]
  [ 4  3  2]]]


In [12]:
array5=array4.reshape(3,2,2)
array5

array([[[13, 12],
        [11, 10]],

       [[ 9,  8],
        [ 7,  6]],

       [[ 5,  4],
        [ 3,  2]]])

In [13]:
array6=np.linspace(1,12,12)
print(array6)
array6.dtype

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.]


dtype('float64')

In [14]:
array7=np.linspace(1,12,12,dtype=int)
print(array7)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [16]:
a = np.zeros( (4,5) ) # 利用 zeros() 函 数 生 成 数 组
print(a)
a.dtype

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


dtype('float64')

In [17]:
np.ones((2,5,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [18]:
np.empty( (3,2) )

array([[  2.20118582e+025,   2.05884232e-071],
       [  5.48773331e-057,   1.38670049e-047],
       [  5.04342478e+180,   1.16712372e+200]])

# Section 10.1.2

In [19]:
a1=np.linspace(1,26,6,dtype=int)
print(a1)
print(a1[3])
print(a1[1:3])
print(a1[:5])
print(a1[2:])
print(a1[-1])
print(a1[-3])
print(a1[:-1])
print(a1[2:-1])

[ 1  6 11 16 21 26]
16
[ 6 11]
[ 1  6 11 16 21]
[11 16 21 26]
26
16
[ 1  6 11 16 21]
[11 16 21]


In [20]:
a2=a1[0:3:1]
print(a2)
a1[0]=19
print(a2[0])

[ 1  6 11]
19


In [21]:
a1[[0,1,4]]
a3=a1[[0,3,2]]
print(a3)
a1[0]=23
print(a3[0])

[19 16 11]
19


In [22]:
na1=np.array(np.arange(24),dtype=int).reshape(4,6)
print(na1)
na1[:2,1:]
na1[[2,3],[2,4]]
na1[2:,[2,4]]
na2=na1.reshape(2,3,4)
print(na2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [23]:
na2[(1,1,2)]
na2[1,1,2]
na2[[1,1,0],[0,1,2],[2,3,1]]
na2[(1,1,1),(0,1,2),(2,3,1)]

array([14, 19, 21])

# Section 10.1.3

In [24]:
ar1=np.array(np.arange(5))
print(ar1)
np.add(ar1,4)
ar2=np.array([2,3,4,5,6])
print(ar2)

[0 1 2 3 4]
[2 3 4 5 6]


In [25]:
ar1+ar2
np.add(ar1,ar2)
np.add(ar1,ar2,ar1)
print(ar1)

[ 2  4  6  8 10]


In [26]:
a = np.array( [10,20,30,50,60] )
b = np.arange( 5 )
print(b)
c=a-b
print(c)

[0 1 2 3 4]
[10 19 28 47 56]


In [27]:
b**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [28]:
10*np.cos(a)

array([-8.39071529,  4.08082062,  1.5425145 ,  9.64966028, -9.5241298 ])

In [29]:
a<40

array([ True,  True,  True, False, False], dtype=bool)

# 1.利用numpy创建一个4阶希尔伯特矩阵

In [31]:
import numpy as np
hilbert = 1/(np.arange(4)+np.arange(1,5)[:,np.newaxis])
print(hilbert)

[[ 1.          0.5         0.33333333  0.25      ]
 [ 0.5         0.33333333  0.25        0.2       ]
 [ 0.33333333  0.25        0.2         0.16666667]
 [ 0.25        0.2         0.16666667  0.14285714]]


# 2.在chapter9的第5题中，创建了持仓份额的字典。现在，利用numpy包获取需要买进的日期及当天的股价

In [34]:
import datetime as dt
import numpy as np
import datetime as dt
import math
dates = [dt.datetime(2015,1,13)+dt.timedelta(i) for i in range(5)]
closes = [7.31,7.28,7.40,7.43,7.41]
prices = {dates[i]:closes[i] for i in range(5)}
prices[dt.datetime(2015,1,20)] = 7.44
dates.append(dt.datetime(2015,1,20))
cash = 10000
share = {dates[0]:0}
for i in range(1,6):
    if prices[dates[i]]>prices[dates[i-1]]:
        buyshare = math.floor(0.5*cash/prices[dates[i]])
        share[dates[i]]= buyshare
        cash=cash-buyshare*prices[dates[i]]+share[dates[i-1]]*prices[dates[i]]
    else:
         share[dates[i]]= 0
buyDates=[np.datetime64(date) for date in share.keys() if share[date]>0]
print(buyDates)
[prices[dt.datetime.
         strptime(np.datetime_as_string(date)[:10],
         	"%Y-%m-%d")] for date in buyDates]

[numpy.datetime64('2015-01-15T00:00:00.000000'), numpy.datetime64('2015-01-16T00:00:00.000000'), numpy.datetime64('2015-01-20T00:00:00.000000')]


[7.4, 7.43, 7.44]

# 3.利用numpy计算出将区间[0,2π]分成1000份后每个端点的余弦值

In [36]:
cosin = np.cos(np.linspace(0,2*np.pi,1001))
print(cosin)

[ 1.          0.99998026  0.99992104 ...,  0.99992104  0.99998026  1.        ]


# 4.利用numpy求下列列表的均值、方差、标准差及中位数

In [40]:
sample = np.array([0.5,1.43,-1.36,-0.16,0.29,-0.59,
	              1.16,-0.33,0.07,-1.36])

print(np.mean(sample))
print(np.var(sample))
print(np.std(sample))
print(np.median(sample))

-0.035
0.789905
0.88876599845
-0.045
